schedule:
  example: # name of command to run (create as many as you want!)
    mintime: 120 # minimum time to wait before executing command(s) (seconds)
    maxtime: 3600 # maximum time to wait before executing command(s) (seconds)
    time: 'Time left until next execution: ' # custom message for time left if you want to allow players access to this command
    runByDefault: false # this boolean sets whether the command starts by default
    commands: # list of commands to run
      - 'say This command will run randomly from 2 minutes to 1 hr!'
      - 'shout this will do the same!'